# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prototype.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import analize as anal

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 378)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.InsertFilepath = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.InsertFilepath.setGeometry(QtCore.QRect(10, 350, 401, 21))
        self.InsertFilepath.setObjectName("InsertFilepath")
        self.InsertFilepath.setPlaceholderText("insert path here")

        self.FIlePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.FIlePathLabel.setGeometry(QtCore.QRect(10, 330, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.FIlePathLabel.setFont(font)
        self.FIlePathLabel.setObjectName("FIlePathLabel")

        self.AnalizeModeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.AnalizeModeCheckbox.setGeometry(QtCore.QRect(660, 300, 81, 17))
        self.AnalizeModeCheckbox.setObjectName("AnalizeModeCheckbox")

        self.SearchCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.SearchCheckBox.setGeometry(QtCore.QRect(560, 230, 141, 17))
        self.SearchCheckBox.setObjectName("SearchCheckBox")

        self.MaxDepthSpinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.MaxDepthSpinbox.setGeometry(QtCore.QRect(570, 350, 42, 22))
        self.MaxDepthSpinbox.setObjectName("MaxDepthSpinbox")

        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(620, 320, 121, 51))
        self.Run.setObjectName("Run")

        self.Group = QtWidgets.QGroupBox(self.centralwidget)
        self.Group.setGeometry(QtCore.QRect(320, 0, 401, 211))
        self.Group.setObjectName("Group")

        self.printoutput = QtWidgets.QTextBrowser(self.Group)
        self.printoutput.setGeometry(QtCore.QRect(0, 30, 211, 181))
        self.printoutput.setObjectName("printoutput")
        self.printoutput.horizontalScrollBar()
        self.printoutput.horizontalScrollBar().setValue(0)
        self.printoutput.setLineWrapMode(False)

        self.ExtensionOutput = QtWidgets.QListWidget(self.Group)
        self.ExtensionOutput.setGeometry(QtCore.QRect(220, 30, 181, 181))
        self.ExtensionOutput.setObjectName("ExtensionOutput")

        self.TableLabel = QtWidgets.QLabel(self.Group)
        self.TableLabel.setGeometry(QtCore.QRect(220, 10, 47, 13))
        self.TableLabel.setObjectName("TableLabel")
        
        self.MaxdepthLabel = QtWidgets.QLabel(self.centralwidget)
        self.MaxdepthLabel.setGeometry(QtCore.QRect(516, 350, 51, 20))
        self.MaxdepthLabel.setObjectName("MaxdepthLabel")

        self.Organizerlabel = QtWidgets.QLabel(self.centralwidget)
        self.Organizerlabel.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.Organizerlabel.setObjectName("Organizerlabel")
        self.OrganizerTable = QtWidgets.QTableWidget(self.centralwidget)
        self.OrganizerTable.setGeometry(QtCore.QRect(0, 30, 211, 171))
        self.OrganizerTable.setObjectName("OrganizerTable")
        self.OrganizerTable.setColumnCount(2)
        self.OrganizerTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.OrganizerTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrganizerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrganizerTable.setHorizontalHeaderItem(1, item)

        self.NewRow = QtWidgets.QPushButton(self.centralwidget)
        self.NewRow.setGeometry(QtCore.QRect(0, 200, 75, 23))
        self.NewRow.setObjectName("NewRow")

        self.RemoveLastRow = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveLastRow.setGeometry(QtCore.QRect(80, 200, 111, 23))
        self.RemoveLastRow.setObjectName("RemoveLastRow")

        self.Searchlabel = QtWidgets.QLabel(self.centralwidget)
        self.Searchlabel.setGeometry(QtCore.QRect(320, 210, 91, 16))
        self.Searchlabel.setObjectName("Searchlabel")

        self.Search = QtWidgets.QLineEdit(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(320, 230, 231, 20))
        self.Search.setObjectName("Search")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #Logic Ui dibawah

        self.Run.clicked.connect(self.checkprint)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FIlePathLabel.setText(_translate("MainWindow", "File Path"))
        self.AnalizeModeCheckbox.setText(_translate("MainWindow", "AnalizeMode"))
        self.SearchCheckBox.setText(_translate("MainWindow", "Search mode"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.Group.setTitle(_translate("MainWindow", "Print Result"))
        self.TableLabel.setText(_translate("MainWindow", "Table"))
        self.MaxdepthLabel.setText(_translate("MainWindow", "Maxdepth"))
        self.Organizerlabel.setText(_translate("MainWindow", "Organizer/Search"))
        item = self.OrganizerTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.OrganizerTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Dir Name"))
        item = self.OrganizerTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File List"))
        self.NewRow.setText(_translate("MainWindow", "New Row"))
        self.RemoveLastRow.setText(_translate("MainWindow", "Remove Last Row"))
        self.Searchlabel.setText(_translate("MainWindow", "search query"))\

    def checkprint(self):
        path = self.InsertFilepath.toPlainText()
        self.printoutput.clear()
        self.ExtensionOutput.clear()
        if self.SearchCheckBox.isChecked() == True:
            searchQuery = self.Search.text()
            print(searchQuery)
        else: searchQuery = None

        if self.AnalizeModeCheckbox.isChecked() == True:
            result , analizedFiles , count , sizeofdir , listOfFoundFiles ,foundfiles , numberfoundfiles = anal.list_files(path,3,searchQuery)
            self.printoutput.append(result)
            for i in analizedFiles:
                self.ExtensionOutput.addItem(i + ' :' + str(analizedFiles[i]))
            self.printoutput.append('\n')
            self.printoutput.append('|-|-|ANALIZED DATA FROM DIRECTORY|-|-|')
            self.printoutput.append('\n')
            self.printoutput.append('File Found In the Directory is :' + str(count))
            self.printoutput.append(f'Directory size is {sizeofdir} MB')
            if self.SearchCheckBox.isChecked() ==True:
                self.printoutput.append('\n')
                self.printoutput.append('|-|-|SEARCHED DATA FROM DIRECTORY|-|-|')
                self.printoutput.append('\n')
                self.printoutput.append(f"file is found : {len(listOfFoundFiles)} " + f" the search query is : -{searchQuery}-")
                self.printoutput.append('\n')
                self.printoutput.append(foundfiles)

                
x = 'C:/Users/NABEL/OneDrive/Desktop/Testing Folder - Copy'

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
